### ISSUE TITLE
example.py throws an exception

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/py-kive-api#2]
Exception thrown by the Kive fleet manager while running `example.py`:

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 154, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8: ordinal not in range(128)
Logged from file models.py, line 721
```

Configuration:
- py-kive-api commit 721657f8396b36b71e23e27ca6cbb2602cf9ad98
- cfe-lab/Kive@f55f9e77ee276adb09025c78c2bdd112ea0c382c
- Kive database reset to `demo`

**Comment by ArtPoon** [comment]
Exception is being thrown in `method/models.py`:

```
    def _poll_stream(self, source_stream, source_name, dest_streams):
        """ Redirect all input from source_stream to all the dest_streams

        This is a helper function for run_code, like the Unix tee command.
        @param source_stream: an input stream to redirect
        @param dest_streams: a sequence of streams to redirect output to
        """
        for line in source_stream:
            self.logger.debug('%s: %s', source_name, line.rstrip()) #drops \n

            for stream in dest_streams:
                stream.write(line)
```

**Comment by ArtPoon** [comment]
This particular message seems to be associated with running `coverage_plots.R` in the miseq pipeline.
I also encountered another problem (`sam_g2p.sh` stderr indicating Ruby failure to load `alignment` shared library) that I will record as a separate issue.

**Comment by ArtPoon** [comment]
Fixed by modifying the following line:

```
self.logger.debug('%s: %s', source_name, line.rstrip().decode('utf-8')) #drops \n
```

Will commit after debugging issue #3

**Comment by jjh13** [comment]
K. I'm actually trying to reproduce this anyway. I can get the run to start no problem from the API, I'm just missing some dependencies to actually test the pipeline.

**Comment by jjh13** [comment]
This causes a 500 error, correct? I should probably devise a nice way of catching those in py-kive-api, if there isn't one already.

**Comment by donkirkby** [comment]
Unless you're going to add context to the 500 error, @jjh13, you should probably just let it bubble up to the client. The client should know how to deal with it by retrying or giving up.

It might be useful to put some more error handling code in one of the examples, though. I see you have an example that catches the `KiveMalformedDataException`, are there any other examples that would be useful?

**Comment by jjh13** [comment]
There are a few others, they're declared in the `__init__.py` file in the kiveapi directory.
