### ISSUE TITLE
stderr not being reported to console

### ISSUE THREAD

**Issue by ArtPoon** [cfe-lab/py-kive-api#3]
The default MiSeq pipeline that is distributed in the Kive `demo` fails on my workstation, possibly  because of a version conflict in Ruby when loading `alignment.bundle`:

```
1: sam_g2p.sh stderr
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Volumes/Crawlspace/media/Sandboxes/userkive_run1_VD7U3D/step5/alignment.bundle, 9): Symbol not found: __ZNSs4_Rep20_S_empty_rep_storageE (LoadError)

  Referenced from: /Volumes/Crawlspace/media/Sandboxes/userkive_run1_VD7U3D/step5/alignment.bundle
```

This information only appeared because I inserted some print statements into Kive `method/models.py` in the Method class function `_poll_stream`.  This should probably be made more visible.

**Comment by donkirkby** [comment]
Migrated this issue to cfe-lab/Kive#431.

**Comment by donkirkby** [comment]
Reopened, because I misunderstood where the problem was. Art wants the Kive api class to raise an exception when the run fails.

**Comment by jjh13** [comment]
I patched this as of d0337873cc15c9003e0fddec4bba924098fe336c

Whenever the server is polled for the run status, it checks whether the run has failed, and throws a KiveRunFailedException.

**Comment by donkirkby** [comment]
It seems odd for the polling to raise the exception. I would suggest the following:

```
class KiveApi:
    def submit_pipeline():
        ...
        return RunStatus()
    def run_pipeline()
        run_status = self.submit_pipeline()
        run_status.wait()
        return run_status

class RunStatus:
    def wait():
        # do polling here, so client doesn't have to
        while True:
            sleep()
            status = self.get_status()
            if status == bad_status:
                raise KiveRunFailedException()
            if status == done_status:
                break
     def get_status():
            ...
```

One other thing, it might be helpful if all the exceptions derive from a KiveException base class.

**Comment by donkirkby** [comment]
Moved this issue to cfe-lab/Kive#460, because this project has merged into the Kive repository.
